from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import cm
import os
from typing import Dict, Any

class MatchReportGenerator:
    def __init__(self, output_dir: str = "reports"):
        self.output_dir = output_dir
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)

    def generate_match_summary_pdf(self, match_data: Dict[str, Any]) -> str:
        """
        Genera un reporte PDF profesional para una partida.
        """
        file_path = os.path.join(self.output_dir, f"report_{match_data['id']}.pdf")
        c = canvas.Canvas(file_path, pagesize=A4)
        width, height = A4

        # Header - VAL Tactical War Room
        c.setFillColor(colors.HexColor("#FF4655"))
        c.rect(0, height - 3*cm, width, 3*cm, fill=1, stroke=0)
        
        c.setFillColor(colors.white)
        c.setFont("Helvetica-Bold", 24)
        c.drawString(1*cm, height - 2*cm, "VALORANT TACTICAL REPORT")
        
        c.setFont("Helvetica", 10)
        c.drawString(width - 4*cm, height - 1.5*cm, f"ID: {match_data['id'][:8]}")

        # Match Overview
        c.setFillColor(colors.black)
        c.setFont("Helvetica-Bold", 16)
        c.drawString(1*cm, height - 5*cm, f"Match: {match_data['map_name']} ({match_data['result']})")
        c.setFont("Helvetica", 12)
        c.drawString(1*cm, height - 5.7*cm, f"Score: {match_data['score']} | Date: {match_data['date']}")

        # Performance Table Placeholder
        c.setStrokeColor(colors.lightgrey)
        c.line(1*cm, height - 7*cm, width - 1*cm, height - 7*cm)
        
        c.setFont("Helvetica-Bold", 12)
        c.drawString(1*cm, height - 8*cm, "ROSTER PERFORMANCE")
        
        y = height - 9*cm
        c.setFont("Helvetica", 10)
        for p in match_data.get('players', []):
            c.drawString(1.5*cm, y, f"{p['name']} ({p['agent']})")
            c.drawString(6*cm, y, f"ACS: {p['acs']}")
            c.drawString(9*cm, y, f"KDA: {p['kda']}")
            y -= 0.6*cm

        # AI Tactical Insight Box
        c.setFillColor(colors.HexColor("#FFF8E1")) # Light Amber
        c.rect(1*cm, 2*cm, width - 2*cm, 4*cm, fill=1, stroke=1)
        
        c.setFillColor(colors.black)
        c.setFont("Helvetica-Bold", 10)
        c.drawString(1.5*cm, 5.4*cm, "TACTICAL AI INSIGHTS (GEMINI 2.0 FLASH)")
        
        c.setFont("Helvetica-Oblique", 9)
        text_object = c.beginText(1.5*cm, 5*cm)
        text_object.textLines(match_data.get('ai_insight', 'No analysis available yet.'))
        c.drawText(text_object)

        # Footer
        c.setFont("Helvetica", 8)
        c.setFillColor(colors.grey)
        c.drawCentredString(width/2, 1*cm, "Generated by VAL Analytics Platform (Franchise Tier Edition)")

        c.showPage()
        c.save()
        return file_path
